on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC https://docs.npmjs.com/trusted-publishers
  contents: read

jobs:
  dry-run:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Check formatting
        run: make format-check
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - name: Dry run
        if: github.actor != 'dependabot[bot]'
        run: npm publish --dry-run

  publish:
    needs: dry-run
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment:
      name: main
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
      - run: npm ci
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - name: Publish
        run: npm publish --provenance --access public
